[phases.setup]
nixPkgs = ['nodejs_20', 'pnpm']

[phases.install]
cmds = [
  'pnpm install --frozen-lockfile',
  'npx playwright install-deps chromium',
  'npx playwright install chromium'
]

[phases.build]
cmds = ['pnpm build']

[start]
cmd = 'cd apps/web && pnpm start'
